
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/media_kit_block.dart';

class MediaKitExporter {
  static Future<void> exportPdf(List<MediaKitBlock> blocks, String userHandle) async {
    final pdf = pw.Document();
    
    // Load a font (using standard Helvetica for now, ideally we load custom fonts)
    final font = await PdfGoogleFonts.poppinsRegular();
    final fontBold = await PdfGoogleFonts.poppinsBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        theme: pw.ThemeData.withFont(
          base: font,
          bold: fontBold,
        ),
        build: (pw.Context context) {
          return [
            ...blocks.map((block) => _buildPdfBlock(block)),
            pw.SizedBox(height: 40),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                "Generated by MyManager.ai",
                style: const pw.TextStyle(color: PdfColors.grey500, fontSize: 10),
              ),
            )
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'MediaKit_\$userHandle.pdf',
    );
  }

  static pw.Widget _buildPdfBlock(MediaKitBlock block) {
    // Map our Flutter blocks to PDF widgets
    switch (block.type) {
      case BlockType.hero:
        final title = block.data['title'] ?? 'Media Kit';
        final subtitle = block.data['subtitle'] ?? '';
        return pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.symmetric(vertical: 40),
          decoration: pw.BoxDecoration(
            color: PdfColors.black,
            borderRadius: pw.BorderRadius.circular(0),
          ),
          child: pw.Column(
            children: [
              pw.Text(
                title.toUpperCase(),
                style: pw.TextStyle(
                  fontSize: 32,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.amber,
                ),
                textAlign: pw.TextAlign.center,
              ),
              if (subtitle.isNotEmpty)
                pw.Padding(
                  padding: const pw.EdgeInsets.only(top: 10),
                  child: pw.Text(
                    subtitle,
                    style: const pw.TextStyle(
                      fontSize: 16,
                      color: PdfColors.white,
                    ),
                    textAlign: pw.TextAlign.center,
                  ),
                ),
            ],
          ),
        );

      case BlockType.stats:
        final List<dynamic> stats = block.data['items'] ?? [];
        return pw.Container(
          margin: const pw.EdgeInsets.symmetric(vertical: 20),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
            children: stats.map((stat) {
              return pw.Column(
                children: [
                   pw.Text(
                    stat['value'] ?? '0',
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.amber,
                    ),
                  ),
                  pw.Text(
                    (stat['label'] ?? '').toUpperCase(),
                    style: const pw.TextStyle(
                      fontSize: 10,
                      color: PdfColors.grey800,
                    ),
                  ),
                ],
              );
            }).toList(),
          ),
        );
      
      case BlockType.about:
        return pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 20),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
               pw.Text(
                block.data['title'] ?? 'About Me',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18),
              ),
              pw.SizedBox(height: 8),
              pw.Text(
                block.data['text'] ?? '',
                style: const pw.TextStyle(fontSize: 12, lineSpacing: 1.5),
              ),
            ],
          ),
        );

       case BlockType.pricing:
        final List<dynamic> services = block.data['items'] ?? [];
        return pw.Container(
          margin: const pw.EdgeInsets.symmetric(vertical: 20),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
               pw.Text(
                "SERVICES & RATES",
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18),
              ),
              pw.SizedBox(height: 12),
              ...services.map((service) {
                return pw.Container(
                  margin: const pw.EdgeInsets.only(bottom: 8),
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: pw.BorderRadius.circular(4),
                  ),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text(service['title'] ?? 'Service', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text(service['price'] ?? 'Contact', style: const pw.TextStyle(color: PdfColors.green700)),
                    ],
                  ),
                );
              }).toList(),
            ],
          ),
        );

      default:
        // Generic fallback for Logos or other unmapped types
        return pw.Container();
    }
  }
}
