import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import '../../core/constants/api_constants.dart';
import '../../core/services/auth_service.dart';
import '../../core/services/gemini_service.dart';
import 'models/media_kit_block.dart';
import 'widgets/media_kit_blocks.dart';
import 'services/media_kit_exporter.dart';

class MediaKitScreen extends StatefulWidget {
  const MediaKitScreen({super.key});

  @override
  State<MediaKitScreen> createState() => _MediaKitScreenState();
}

class _MediaKitScreenState extends State<MediaKitScreen> {
  final _inputController = TextEditingController();
  late final GeminiService _geminiService;
  
  bool _isGenerating = false;
  List<MediaKitBlock>? _generatedBlocks;
  String _loadingMessage = "Initializing AI Art Director...";

  @override
  void initState() {
    super.initState();
    _geminiService = GeminiService(ApiConstants.geminiApiKey);
  }

  Future<void> _generateMediaKit() async {
    if (_inputController.text.isEmpty) return;

    setState(() {
      _isGenerating = true;
      _loadingMessage = "Analyzing your profile...";
    });

    // Simulated Steps for UX
    await Future.delayed(1.seconds);
    setState(() => _loadingMessage = "Structuring layout...");
    await Future.delayed(1.2.seconds);
    setState(() => _loadingMessage = "Generating copy & design...");

    try {
      final auth = context.read<AuthService>();
      final contextString = "Context: I am a creator in the \${auth.userNiche} niche with \${auth.userFollowers} followers. My Handle is \${auth.userHandle}.";
      final fullPrompt = "\$contextString User Input: \${_inputController.text}";

      final blocks = await _geminiService.generateMediaKit(fullPrompt);
      
      if (mounted) {
        setState(() {
          _generatedBlocks = blocks;
          _isGenerating = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isGenerating = false);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Error: \$e")));
      }
    }
  }

  Future<void> _exportPdf() async {
    if (_generatedBlocks == null) return;
    final auth = context.read<AuthService>();
    await MediaKitExporter.exportPdf(_generatedBlocks!, auth.userHandle);
  }

  @override
  Widget build(BuildContext context) {
    // If we have blocks, show the rendered kit
    if (_generatedBlocks != null) {
      return Scaffold(
        backgroundColor: const Color(0xFF0B0C0E), // Keep app dark
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back, color: Colors.white),
            onPressed: () => setState(() => _generatedBlocks = null),
          ),
          centerTitle: true,
          title: Text("YOUR MEDIA KIT", style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w900, letterSpacing: 2.0, color: Colors.white54)),
          actions: [
            IconButton(
              icon: const Icon(Icons.edit, color: Colors.white),
              onPressed: () {}, // TODO: Edit Mode
            ),
             IconButton(
              icon: const Icon(Icons.download, color: Colors.white),
              onPressed: _exportPdf,
            ),
          ],
        ),
        body: Center(
          child: Container(
            constraints: const BoxConstraints(maxWidth: 850), // Standard Web width
            margin: const EdgeInsets.symmetric(vertical: 20, horizontal: 16),
            decoration: BoxDecoration(
              color: Colors.white, // The "Paper"
              borderRadius: BorderRadius.zero, // Paper is sharp
              boxShadow: [
                BoxShadow(color: Colors.black.withValues(alpha: 0.5), blurRadius: 40, offset: const Offset(0, 20)),
              ]
            ),
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  for (var block in _generatedBlocks!)
                    _renderBlock(block),
                  const SizedBox(height: 50),
                   // Watermark
                  Center(
                    child: Padding(
                      padding: const EdgeInsets.all(20.0),
                      child: Text("Generated by My Manager.ai", style: GoogleFonts.inter(color: Colors.black26, fontSize: 10)),
                    ),
                  )
                ],
              ),
            ),
          ),
        ),
      );
    }

    // Input Mode
    return Scaffold(
      extendBodyBehindAppBar: true,
      backgroundColor: const Color(0xFF0B0C0E), // High-End Charcoal
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: Stack(
        children: [
          // Ambient Orb (Consistent with Dashboard)
          Positioned(
            top: -200,
            right: -100, // Positioned differently for variety
            child: Container(
              width: 500,
              height: 500,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [
                    const Color(0xFF1E1B4B).withValues(alpha: 0.2), 
                    Colors.transparent,
                  ],
                  stops: const [0.0, 1.0],
                ),
              ),
              child: BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 80, sigmaY: 80),
                child: const SizedBox(),
              ),
            ),
          ),
          
          Center(
            child: Container(
              constraints: const BoxConstraints(maxWidth: 700),
              padding: const EdgeInsets.all(32),
              margin: const EdgeInsets.all(24),
              child: _isGenerating ? _buildLoadingState() : _buildInputForm(),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInputForm() {
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Icon(Icons.auto_awesome, size: 48, color: const Color(0xFF818CF8)).animate().scale(duration: 600.ms, curve: Curves.easeOutBack),
        const SizedBox(height: 24),
        Text(
          "AI ART DIRECTOR",
          style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w900, color: const Color(0xFF6366F1), letterSpacing: 2.0),
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 12),
        Text(
          "Create your Media Kit",
          style: GoogleFonts.inter(fontSize: 32, fontWeight: FontWeight.bold, color: const Color(0xFFEDEDED), letterSpacing: -1.0),
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 12),
        Text(
          "Paste your bio, metrics, or just describe your vibe.\nOur AI will design a professional kit in seconds.",
          style: GoogleFonts.inter(fontSize: 15, color: const Color(0xFFA1A1AA), height: 1.5),
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 48),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
          decoration: BoxDecoration(
            color: const Color(0xFF1A1C1E),
            borderRadius: BorderRadius.circular(20),
            border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
          ),
          child: TextField(
            controller: _inputController,
            style: GoogleFonts.inter(color: const Color(0xFFEDEDED), fontSize: 16, height: 1.5),
            maxLines: 5,
            decoration: InputDecoration(
              border: InputBorder.none,
              hintText: "e.g., I'm a tech reviewer with 50k subs focusing on minimal desk setups...",
              hintStyle: GoogleFonts.inter(color: Colors.white24),
            ),
          ),
        ),
        const SizedBox(height: 32),
        ElevatedButton(
          onPressed: _generateMediaKit,
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFFEDEDED), // High contrast button
            foregroundColor: Colors.black,
            padding: const EdgeInsets.symmetric(vertical: 24),
            elevation: 0,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          ),
          child: Text(
            "GENERATE KIT", 
            style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.w800, letterSpacing: 0.5)
          ),
        ),
      ],
    );
  }

  Widget _buildLoadingState() {
     return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        SizedBox(
          width: 60, height: 60, 
          child: CircularProgressIndicator(color: const Color(0xFF6366F1), strokeWidth: 4, backgroundColor: Colors.white.withValues(alpha: 0.05))
        ),
        const SizedBox(height: 40),
        Text(
          _loadingMessage,
          style: GoogleFonts.inter(fontSize: 16, color: const Color(0xFFEDEDED), fontWeight: FontWeight.w500),
        ).animate().fadeIn(duration: 500.ms),
      ],
    );
  }

  Widget _renderBlock(MediaKitBlock block) {
    switch (block.type) {
      case BlockType.hero:
        return HeroHeaderBlock(data: block.data);
      case BlockType.stats:
        return Padding(padding: const EdgeInsets.symmetric(horizontal: 24), child: StatsGridBlock(data: block.data));
      case BlockType.logos:
        return Padding(padding: const EdgeInsets.symmetric(horizontal: 24), child: BrandLogosBlock(data: block.data));
      case BlockType.about:
        return Padding(padding: const EdgeInsets.symmetric(horizontal: 24), child: AboutSectionBlock(data: block.data));
      case BlockType.pricing:
        return Padding(padding: const EdgeInsets.symmetric(horizontal: 24), child: PricingTableBlock(data: block.data));
      case BlockType.contact:
        return ContactSectionBlock(data: block.data);
      default:
        return const SizedBox.shrink();
    }
  }
}
